modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="create_brass_coated" #mandatory
version="0.2-1.18.2" #mandatory
displayName="Create: Brass Coated" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/create-brass-coated"
logoFile="brussy.png" #optional
authors="InJir" #optional
description='''
An addon to Create to coat andesite blocks with brass!
'''
[[dependencies.create_brass_coated]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.create_brass_coated]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.create_brass_coated]]
modId="create"
mandatory=true
versionRange="[0.5.0.g,)"
ordering="NONE"
side="BOTH"
